packages:
  - apps/*
  - packages/*

overrides:
  'deepmerge-ts@<8.0.0': 8.0.2
  'nanoid@<3.3.18': 3.3.18

confirmModulesPurge: false
allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  unrs-resolver: true
